In [1]:
import torch

In [2]:

x = torch.rand(100, 16, 784)

layer = torch.nn.BatchNorm1d(16)

out = layer(x)

print(out)
print(layer.running_mean)
print(layer.running_var)


tensor([[[ 0.5238, -0.5910,  0.8068,  ..., -0.2934, -1.2693, -1.5298],
         [ 0.6724,  1.2896, -0.7805,  ..., -0.4318, -1.6690, -1.5545],
         [ 0.8752,  0.3884, -0.5845,  ..., -0.2856, -0.4804, -1.3229],
         ...,
         [ 0.1951,  1.5759,  1.0439,  ..., -1.1725, -0.9614, -0.4822],
         [ 1.6429, -0.5259, -0.0873,  ..., -0.7100, -0.9021,  0.8490],
         [-0.3384,  1.0788,  0.6694,  ..., -1.4507,  0.7727, -0.2185]],

        [[-0.5598, -0.9479,  1.3348,  ...,  0.8142,  1.5094, -0.1033],
         [-1.3853,  0.9320, -0.3289,  ...,  1.7281,  1.4923,  1.1871],
         [ 1.2395,  1.4396, -0.4532,  ..., -1.5733,  1.7177, -0.6079],
         ...,
         [ 1.1428,  1.6792,  0.4666,  ..., -1.4264, -1.5394, -1.5162],
         [-1.3906, -0.1497,  0.3801,  ..., -1.2636,  0.4959,  0.2480],
         [ 1.5341,  1.4239, -0.5555,  ..., -0.1073,  0.6942, -1.7019]],

        [[-0.9337,  0.4269,  0.2124,  ...,  0.8844,  1.0774, -0.2960],
         [-0.6532,  1.6552,  0.8816,  ..., -1

In [3]:
x = torch.rand(1, 16, 7 ,7)
x.shape

torch.Size([1, 16, 7, 7])

In [4]:
layer = torch.nn.BatchNorm2d(16)
out = layer(x)
print(out)
print(layer.weight)
print(layer.bias)

tensor([[[[ 1.6282e+00, -6.2623e-01, -1.5295e+00, -5.6795e-01, -5.6229e-01,
           -5.6195e-01,  2.6946e-01],
          [ 1.0362e+00,  7.5190e-01,  1.2177e+00, -9.9298e-01,  4.7493e-01,
           -1.2940e+00, -2.1230e-01],
          [ 7.4873e-01,  5.1002e-01,  1.3553e+00, -1.0552e+00, -1.6162e+00,
           -1.3901e+00,  1.4295e+00],
          [-7.3129e-01, -8.7200e-01,  1.1159e+00, -1.3861e+00, -1.3000e+00,
           -5.8728e-01,  6.7587e-01],
          [-1.1005e+00, -1.3261e+00,  1.5586e+00,  8.9391e-01,  1.1501e+00,
            3.4597e-02, -3.0499e-02],
          [-1.6319e+00,  1.6675e+00,  2.2970e-01,  2.4360e-02,  6.9514e-01,
            6.1753e-01,  5.7304e-01],
          [-9.7596e-01,  1.8991e-01, -1.0656e+00,  1.2225e+00,  8.8460e-01,
            7.2979e-01, -2.6888e-01]],

         [[-3.3771e-01,  1.2217e+00,  2.1099e-01, -3.6938e-01,  1.6604e+00,
           -6.6011e-02, -9.4036e-01],
          [ 1.0242e+00, -8.9422e-01,  1.2023e+00, -1.0612e+00, -4.4811e-02,
          

In [5]:
vars(layer)

{'training': True,
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0514, 0.0460, 0.0475, 0.0525, 0.0456, 0.0534, 0.0493, 0.0453, 0.0470,
                       0.0542, 0.0462, 0.0461, 0.0468, 0.0539, 0.0450, 0.0559])),
              ('running_var',
               tensor([0.9076, 0.9099, 0.9089, 0.9090, 0.9080, 0.9077, 0.9075, 0.9077, 0.9096,
                       0.9068, 0.9076, 0.9107, 0.9087, 0.9062, 0.9066, 0.9077])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': OrderedDict(),
 

In [6]:
# x = torch.rand(100, 16, 784)
layer.eval()
torch.nn.BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

out = layer(x)
print(out)
print(layer.weight)
print(layer.bias)
vars(layer)

tensor([[[[ 9.5211e-01,  3.0558e-01,  4.6539e-02,  3.2230e-01,  3.2392e-01,
            3.2402e-01,  5.6245e-01],
          [ 7.8233e-01,  7.0080e-01,  8.3437e-01,  2.0041e-01,  6.2137e-01,
            1.1407e-01,  4.2429e-01],
          [ 6.9989e-01,  6.3143e-01,  8.7384e-01,  1.8255e-01,  2.1689e-02,
            8.6531e-02,  8.9512e-01],
          [ 2.7545e-01,  2.3510e-01,  8.0520e-01,  8.7676e-02,  1.1235e-01,
            3.1675e-01,  6.7900e-01],
          [ 1.6957e-01,  1.0486e-01,  9.3215e-01,  7.4153e-01,  8.1498e-01,
            4.9509e-01,  4.7643e-01],
          [ 1.7189e-02,  9.6336e-01,  5.5105e-01,  4.9216e-01,  6.8452e-01,
            6.6227e-01,  6.4951e-01],
          [ 2.0529e-01,  5.3963e-01,  1.7958e-01,  8.3575e-01,  7.3886e-01,
            6.9446e-01,  4.0806e-01]],

         [[ 3.2338e-01,  8.3300e-01,  5.0269e-01,  3.1303e-01,  9.7635e-01,
            4.1217e-01,  1.2643e-01],
          [ 7.6847e-01,  1.4151e-01,  8.2666e-01,  8.6948e-02,  4.1910e-01,
          

{'training': False,
 '_parameters': OrderedDict([('weight',
               Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0514, 0.0460, 0.0475, 0.0525, 0.0456, 0.0534, 0.0493, 0.0453, 0.0470,
                       0.0542, 0.0462, 0.0461, 0.0468, 0.0539, 0.0450, 0.0559])),
              ('running_var',
               tensor([0.9076, 0.9099, 0.9089, 0.9090, 0.9080, 0.9077, 0.9075, 0.9077, 0.9096,
                       0.9068, 0.9076, 0.9107, 0.9087, 0.9062, 0.9066, 0.9077])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': 