In [17]:
import torch

In [18]:

x = torch.rand(100, 16, 784)

layer = torch.nn.BatchNorm1d(16)

out = layer(x)

print(out)
print(layer.running_mean)
print(layer.running_var)


tensor([[[ 1.5263e+00,  1.3422e+00,  2.8654e-01,  ..., -1.4448e+00,
          -9.8507e-01,  1.1497e+00],
         [ 1.8070e-01, -1.1352e+00, -1.1014e+00,  ...,  5.8339e-01,
           1.0797e+00, -1.0673e+00],
         [-9.0867e-01,  2.0595e-01, -4.4556e-01,  ..., -7.4296e-01,
           1.1788e+00, -3.8316e-01],
         ...,
         [-3.3734e-01, -9.0128e-01,  3.1340e-01,  ..., -7.8484e-01,
          -3.4270e-01,  1.4307e+00],
         [ 5.2117e-01,  6.0831e-01,  1.0984e+00,  ..., -5.3943e-01,
          -1.5142e+00,  7.5842e-01],
         [ 1.6583e+00, -3.1434e-01, -7.9544e-01,  ...,  1.4237e-01,
           5.7827e-01, -6.0900e-01]],

        [[-1.4068e+00,  8.7571e-01,  4.3200e-01,  ...,  4.2408e-01,
          -1.9456e-01,  3.7469e-01],
         [ 8.2137e-01,  9.3426e-01, -1.9407e-01,  ...,  8.8859e-01,
           1.5287e+00,  2.3847e-01],
         [ 1.5509e+00,  8.3575e-02, -6.3627e-01,  ..., -1.7192e+00,
          -9.2913e-01,  4.4348e-01],
         ...,
         [-1.1362e-01, -1

In [19]:
x = torch.rand(1, 16, 7 ,7)
x.shape

torch.Size([1, 16, 7, 7])

In [20]:
layer = torch.nn.BatchNorm2d(16)
out = layer(x)
print(out)
print(layer.weight)
print(layer.bias)

tensor([[[[-1.5638, -0.1289, -0.9661,  1.2189,  1.3759,  0.4085, -1.6308],
          [ 0.0358,  0.7740, -0.2823,  1.2101, -0.5264,  1.2033, -0.1176],
          [-0.9823,  1.3682, -0.9203, -0.3494, -0.5234, -1.7408,  1.0496],
          [ 0.4184, -0.3451,  0.7338,  1.1251,  1.2453, -0.0114,  0.8020],
          [ 0.1216,  0.5796, -1.5157, -0.5220, -1.4256, -1.7020, -1.2729],
          [ 0.5817,  0.2309,  0.8572,  0.2358, -1.7317,  0.4695,  1.1093],
          [ 1.3807,  0.7801, -0.2871, -1.7941, -0.7313,  0.8059,  0.9499]],

         [[ 1.3759,  1.3792,  0.6379,  0.6202, -1.0727, -0.1761, -1.2662],
          [-0.9282,  1.4693,  0.7689, -0.8471, -1.4934, -0.2635, -1.0978],
          [ 1.2635, -0.6328, -0.9866, -1.0098,  0.1273, -0.7586,  0.8707],
          [ 0.0991, -0.8246,  1.3539,  0.9457,  1.0235, -0.6238,  1.7001],
          [-1.0883, -1.2108, -0.1440, -0.4192, -0.2138,  0.9055, -1.3931],
          [ 0.8725, -1.0233, -1.1959, -0.7914,  1.3984,  1.6832, -0.6268],
          [ 1.5792,  1.

In [21]:
vars(layer)

{'training': True,
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0569, 0.0485, 0.0523, 0.0490, 0.0464, 0.0500, 0.0516, 0.0455, 0.0477,
                       0.0466, 0.0484, 0.0565, 0.0553, 0.0517, 0.0473, 0.0496])),
              ('running_var',
               tensor([0.9080, 0.9089, 0.9076, 0.9083, 0.9081, 0.9097, 0.9077, 0.9089, 0.9071,
                       0.9087, 0.9088, 0.9075, 0.9109, 0.9095, 0.9095, 0.9105])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': OrderedDict(),
 

In [ ]:
# x = torch.rand(100, 16, 784)
layer.eval()
torch.nn.BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

out = layer(x)
print(out)
print(layer.weight)
print(layer.bias)
vars(layer)

tensor([[[[ 7.6784e-02,  4.9929e-01,  2.5279e-01,  8.9617e-01,  9.4240e-01,
            6.5754e-01,  5.7067e-02],
          [ 5.4781e-01,  7.6515e-01,  4.5412e-01,  8.9357e-01,  3.8225e-01,
            8.9156e-01,  5.0263e-01],
          [ 2.4802e-01,  9.4014e-01,  2.6628e-01,  4.3439e-01,  3.8313e-01,
            2.4665e-02,  8.4632e-01],
          [ 6.6044e-01,  4.3565e-01,  7.5333e-01,  8.6854e-01,  9.0394e-01,
            5.3391e-01,  7.7342e-01],
          [ 5.7306e-01,  7.0793e-01,  9.0949e-02,  3.8354e-01,  1.1747e-01,
            3.6094e-02,  1.6246e-01],
          [ 7.0853e-01,  6.0523e-01,  7.8965e-01,  6.0669e-01,  2.7345e-02,
            6.7550e-01,  8.6390e-01],
          [ 9.4380e-01,  7.6695e-01,  4.5272e-01,  8.9722e-03,  3.2191e-01,
            7.7456e-01,  8.1696e-01]],

         [[ 8.8397e-01,  8.8498e-01,  6.5527e-01,  6.4980e-01,  1.2520e-01,
            4.0304e-01,  6.5256e-02],
          [ 1.6997e-01,  9.1292e-01,  6.9587e-01,  1.9511e-01, -5.1680e-03,
          

{'training': False,
 '_parameters': OrderedDict([('weight',
               Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0569, 0.0485, 0.0523, 0.0490, 0.0464, 0.0500, 0.0516, 0.0455, 0.0477,
                       0.0466, 0.0484, 0.0565, 0.0553, 0.0517, 0.0473, 0.0496])),
              ('running_var',
               tensor([0.9080, 0.9089, 0.9076, 0.9083, 0.9081, 0.9097, 0.9077, 0.9089, 0.9071,
                       0.9087, 0.9088, 0.9075, 0.9109, 0.9095, 0.9095, 0.9105])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': 